language: python
python:
  - 2.7

install:
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - make version=$TRAVIS_PYTHON_VERSION .installed.cfg

script:
  - make tests

notifications:
  irc:
    - "irc.freenode.org#sprint"
